### ISSUE TITLE
Makefile broken for macOS

### ISSUE THREAD

**Issue by wombley** [nahoj/tss#2]
Trying to run make install on macOS will result in the following error, due to a differing version of make:

```shell
$ make install   
mkdir -p "/Users/alasdair/.local/share/tss"
install -Dm644 "/Users/alasdair/Downloads/tss/src"/modules/*.zsh "/Users/alasdair/.local/share/tss"
install: illegal option -- D
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
make: *** [install] Error 64
``` 

This is due to the macOS version of Make not having the -D option - see https://apple.stackexchange.com/questions/201029/install-illegal-option-d

Since you mentioned macOS as a target platform in your introduction post I figured I'd better let you know.

Oddly, looking at the makefile it seems mkdir -p is being used for every target directory anyway - which seems to me to render the D option entirely redundant - it certainly seems to have worked when I removed the D from every install line. However I am NOT an expert with makefiles, I've barely ever even tweaked them, so don't take my word for it.

Thanks for the tool - it's certainly nicer than trying to use regex to rename a bunch of files manually!

**Comment by nahoj** [comment]
Thanks for the report! I think I didn't test it on macOS and just assumed it was likely to work.

Clearly I used `install -D` without knowing what it did; I must have AI-generated it or copy-pasted it. I just removed the option; I hope it works for everyone now.

**Comment by wombley** [comment]
I've just tested the new version, works fine, thanks!
